- hosts: localhost

  pre_tasks:
    - name: Update Brew
      community.general.homebrew:
        update_homebrew: yes

  tasks:
    - include: ansible/tasks/git-setup.yaml
    - include: ansible/tasks/cli-tools.yaml
    - include: ansible/tasks/gui-tools.yaml
    - include: ansible/tasks/zsh.yaml
    - include: ansible/tasks/app-store-apps.yaml
    - include: ansible/tasks/fonts.yaml
    - include: ansible/tasks/osx.yaml
    - include: ansible/tasks/iterm.yaml
    - include: ansible/tasks/node.yaml
    - include: ansible/tasks/vscode.yaml
