- hosts: localhost

  pre_tasks:
    - name: Update Brew
      community.general.homebrew:
        update_homebrew: yes

  tasks:
    - name: Git setup tasks
      include_tasks: ansible/tasks/git-setup.yaml

    - name: CLI tools setup tasks
      include_tasks: ansible/tasks/cli-tools.yaml

    - name: GUI tools setup tasks
      include_tasks: ansible/tasks/gui-tools.yaml

    - name: Zsh setup tasks
      include_tasks: ansible/tasks/zsh.yaml

    - name: App Store apps setup tasks
      include_tasks: ansible/tasks/app-store-apps.yaml

    - name: fonts setup tasks
      include_tasks: ansible/tasks/fonts.yaml

    - name: iTerm setup tasks
      include_tasks: ansible/tasks/iterm.yaml

    - name: Node setup tasks
      include_tasks: ansible/tasks/node.yaml

    - name: VSCode setup tasks
      include_tasks: ansible/tasks/vscode.yaml

    - name: Zed setup tasks
      include_tasks: ansible/tasks/zed.yaml

    - name: Nvim / Lvim setup
      include_tasks: ansible/tasks/nvim.yaml
      
    - name: OSX setup tasks
      include_tasks: ansible/tasks/osx.yaml
