- name: Install Magnet
  ignore_errors: yes
  community.general.mas:
    id: 441258766
    state: latest

- name: Install The Unarchiver
  ignore_errors: yes
  community.general.mas:
    id: 425424353
    state: latest
