- name: Install useful cli packages
  community.general.homebrew:
    name: "{{ item }}"
    state: latest
  with_items:
    - yarn
    - tree
    - curl
    - htop
    - ansible-lint
    - ranger
    - lazydocker
    - mas
    # history jump
    - jump
    # fuzzy finder
    - fzf
    # Github Cli
    - gh
    - lazygit
    - python
    - rust
    - ripgrep
    - go
    - tree-sitter-cli
