- name: Tapping homebrew/cask-fonts
  homebrew_tap:
    name: homebrew/cask-fonts
  tags:
    - install
    - fonts

- name: Installing fonts
  homebrew_cask:
    name:
      - font-hack-nerd-font
      - font-fira-code
      - font-meslo-lg-nerd-font
      - font-meslo-for-powerline
  tags:
    - install
    - fonts
