- name: Tapping homebrew/cask-fonts
  homebrew_tap:
    name: homebrew/cask-fonts

- name: Installing fonts
  homebrew_cask:
    name:
      - font-inconsolata-for-powerline
      - font-hack-nerd-font
      - font-fira-code
      - font-meslo-lg-nerd-font
      - font-meslo-for-powerline
