- name: Install latest Git
  community.general.homebrew:
    name: git
    state: latest

- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "zasadzkimarcin@gmail.com"

- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "Marcin Zasadzki"

- name: Set vim as default git editor
  community.general.git_config:
    name: core.editor
    scope: global
    value: vim

- name: Set global git ignore
  community.general.git_config:
    name: core.excludesfile
    scope: global
    value: ~/.global_gitignore

- name: Set global git default branch name
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main
