- name: Prompt for Git email
  ansible.builtin.pause:
    prompt: "Enter your Git email"
  register: git_email

- name: Install latest Git
  community.general.homebrew:
    name: git
    state: latest

- name: Configure Git email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_email.user_input }}"

- name: Configure Git name
  community.general.git_config:
    name: user.name
    scope: global
    value: "Marcin Zasadzki"

- name: Set vim as default git editor
  community.general.git_config:
    name: core.editor
    scope: global
    value: vim

- name: Set global git ignore
  community.general.git_config:
    name: core.excludesfile
    scope: global
    value: "{{ lookup('ansible.builtin.env', 'HOME') }}/.global_gitignore"

- name: Set default branch name
  community.general.git_config:
    name: init.defaultBranch
    scope: global
    value: main
