- name: Install core packages via brew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
  ignore_errors: true
  with_items:
    - docker
    - google-chrome
    - iterm2
    - ghostty
    - insomnia
    - postman
    - stats
    - sourcetree
    - hammerspoon
    - zed
    - cursor
