- name: Install core packages via brew casks
  community.general.homebrew_cask:
    name: "{{ item }}"
    state: latest
  ignore_errors: true
  with_items:
    - anki
    - aldente
    - brave-browser
    - cheatsheet
    - docker
    - google-chrome
    - http-toolkit
    - firefox
    - iterm2
    - ghostty
    - insomnia
    - ngrok
    - postman
    - stats
    - spotify
    - surfshark
    - sourcetree
    - vlc
    - hammerspoon
    - zed
