- name: Install IntelliJ IDEA
  community.general.homebrew_cask:
    name: intellij-idea
    state: present

- name: Deploy IdeaVim configuration
  ansible.builtin.template:
    src: ../templates/.ideavimrc
    dest: "{{ ansible_env.HOME }}/.ideavimrc"
    mode: "0644"
