- name: Install nvm
  community.general.homebrew:
    name: nvm
    state: latest

- name: Install latest lts version of node
  ansible.builtin.shell: |
    source ~/.zshrc
    nvm install --lts
    nvm alias default
