- name: Install NeoVim
  community.general.homebrew:
    name: neovim
    state: latest

- name: Ensure ~/.config exists
  ansible.builtin.file:
    path: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config"
    state: directory
    mode: "0755"

- name: Copy NeoVim configuration
  ansible.builtin.copy:
    src: ../../.config/nvim/
    dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/.config/nvim/"
    mode: preserve
