- name: Install tmux
  community.general.homebrew:
    name: tmux
    state: latest

- name: Render tmux config
  ansible.builtin.template:
    src: ../templates/.tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    mode: "0644"
