- name: Install Visual Studio Code
  community.general.homebrew_cask:
    name: visual-studio-code
    state: present

- name: Ensure the `code` CLI is available
  ansible.builtin.file:
    src: /Applications/Visual Studio Code.app/Contents/Resources/app/bin/code
    dest: /usr/local/bin/code
    state: link
  become: true

- name: Ensure VSCode User config directory exists
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/Library/Application Support/Code/User"
    state: directory
    mode: "0755"

- name: Copy VSCode settings
  ansible.builtin.copy:
    src: ../templates/vscode-settings.json
    dest: "{{ ansible_env.HOME }}/Library/Application Support/Code/User/settings.json"
    mode: "0644"

- name: Install VSCode extensions
  ansible.builtin.command:
    cmd: code --install-extension {{ item }}
  loop:
    - aaravb.chrome-extension-developer-tools
    - adamhartford.vscode-base64
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - ecmel.vscode-html-css
    - esbenp.prettier-vscode
    - formulahendry.auto-rename-tag
    - frhtylcn.aws-sdk-snippets
    - johnpapa.vscode-peacock
    - lucax88x.codeacejumper
    - mgmcdermott.vscode-language-babel
    - naumovs.color-highlight
    - pflannery.vscode-versionlens
    - streetsidesoftware.code-spell-checker
    - svelte.svelte-vscode
    - VisualStudioExptTeam.vscodeintellicode
    - WallabyJs.quokka-vscode
    - Zignd.html-css-class-completion
    - vscode-icons-team.vscode-icons
  register: vscode_extensions
  changed_when: "'already installed' not in vscode_extensions.stdout"
