- name: Create a default VSCode configuration
  template:
    src: ../templates/vscode-settings.json
    dest: /Users/{{ lookup('env', 'USER') }}/Library/Application Support/Code/User/settings.json
    mode: "0644"
    force: yes

# Add something which ensures path is set here
- name: Install VSCode extensions
  shell: code --install-extension {{ item }}
  with_items:
    - aaravb.chrome-extension-developer-tools
    - adamhartford.vscode-base64
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - ecmel.vscode-html-css
    - esbenp.prettier-vscode
    - formulahendry.auto-rename-tag
    - frhtylcn.aws-sdk-snippets
    - johnpapa.vscode-peacock
    - lucax88x.codeacejumper
    - mgmcdermott.vscode-language-babel
    - naumovs.color-highlight
    - pflannery.vscode-versionlens
    - streetsidesoftware.code-spell-checker
    - svelte.svelte-vscode
    - VisualStudioExptTeam.vscodeintellicode
    - WallabyJs.quokka-vscode
    - Zignd.html-css-class-completion
    - vscode-icons-team.vscode-icons
