- name: Install zsh
  community.general.homebrew:
    name: ["zsh"]
  tags:
    - install
    - zsh
    - productivity

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  changed_when: true
  tags:
    - install
    - zsh
    - productivity
  become: true

- name: Check to see if oh-my-zsh is already installed
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh
  tags:
    - install
    - zsh
    - productivity

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - install
    - zsh
    - productivity
  when: not oh_my_zsh.stat.exists
