- name: Install zsh
  community.general.homebrew:
    name: ["zsh"]

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  changed_when: true
  become: true

- name: Check to see if oh-my-zsh is already installed
  stat:
    path: ~/.oh-my-zsh
  register: oh_my_zsh

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: not oh_my_zsh.stat.exists

- name: Copy ZSH .zshrc file
  template:
    src: ../templates/.zshrc
    dest: ~/
    mode: "0644"
